---
- hosts: banco
  become: yes
  tasks:
    - name: 'Update package'
      apt: 
        update_cache: yes
    - name: 'Instalação de pacotes na máquina DB'
      apt:
        name:
          - mariadb-server
          - wget
          - zip
          - curl
          - vim
          - python3-mysqldb
        state: present

    - name: 'Baixar e extrair arquivo db.zip'
      become: true
      unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/db.zip
        dest: /tmp 
        remote_src: yes

    - name: 'Criação de banco de dados backup'
      mysql_db:
       name: backup
       login_user: root
       login_password: ""
       state: present
    
    - name: 'Importação do banco backup.sql'
      mysql_db:
        login_user: root 
        login_password: ""
        state: import 
        name: backup
        target: /tmp/backup.sql 

    - name: 'Criar e conceder privilegios para usuário express'
      mysql_user: 
        host: '%' 
        login_user: root
        login_password: ""
        name: express 
        password: 'AllSafe0!'
        priv: 'backup.*:ALL'
        state: 'present' 
    
    - name: 'Substituição do 127.0.0.1 por 0.0.0.0'
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'
      notify: Restart Mysql 

  handlers:
    - name: Restart Mysql 
      service: 
        name: mysql 
        state: restarted 
        enabled: yes 
    

