---
- name: 'Updating repositories'
  apt:
    update_cache: yes
  become: true

- name: 'Installing PHP 7.4'
  apt:
    name:
      - php7.4
      - php-pear
      - php7.4-curl
      - php7.4-gd
      - php7.4-intl
      - php7.4-xmlrpc
      - php7.4-mysql
  become: true
# tasks file for php7.4
