---
- name: 'Updating repositories'
  apt:
    update_cache: yes
  become: true

- name: 'Installing mariadb server'
  apt:
    name:
      - mariadb-server
      - python3-mysqldb
    state: present

- name: 'Downloading the database'
  become: true
  unarchive:
    src: https://github.com/rogerramossilva/devops/raw/master/db.zip
    dest: /tmp 
    remote_src: yes

- name: 'Creating the database'
  mysql_db:
    name: backup
    login_user: root
    login_password: ""
    state: present

- name: 'Importing the database'
  mysql_db:
    login_user: root 
    login_password: ""
    state: import 
    name: backup
    target: /tmp/backup.sql

- name: 'Creating application user'
  mysql_user: 
    host: '%' 
    login_user: root
    login_password: ""
    name: express 
    password: 'AllSafe0!'
    priv: 'backup.*:ALL'
    state: 'present'

- name: 'Freeing up access to the bank for everyone'
  replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '127\.0\.0\.1'
    replace: '0.0.0.0'
  notify: Restart Mysql

# tasks file for mariadb
