---
- name: 'Updating repositories'
  apt:
    update_cache: yes
  become: true

- name: 'Installing default programs'
  apt:
    name:
      - wget
      - curl
      - tcpdump
      - nmap
      - zip
      - net-tools
    state: present
  become: true